learning_templates/basic_app/urls.py
from django.urls import path
from basic_app import views

#TEMPLATE TAGGING
app_name = 'basic_app'

urlpatterns = [
    path('relative/',views.relative,name='relative'),
    path('other/',views.other,name='other')
]

learning_templates/learning_templates/urls.py
from django.contrib import admin
from django.urls import path, include
from basic_app import views
urlpatterns = [
    path('',views.index,name='index'),
    path('basic_app/',include('basic_app.urls')),
    path('admin/', admin.site.urls),
]

learning_templates/basic_app/models.py
from django.db import models

# Create your models here.

learning_templates/basic_app/views.py
from django.shortcuts import render

# Create your views here.

def index(request):
    return render(request,'basic_app/index.html')

def other(request):
    return render(request,'basic_app/other.html')

def relative(request):
    return render(request,'basic_app/relative_url_templates.html')

learning_templates/basic_app/templates/basic_app/base.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title></title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
  </head>
  <body>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
      <div class="container">
        <ul class="nav navbar-nav">
          <li><a class="navbar-brand" href="{% url 'index'%}">BRAND</a></li>
          <li><a class="nav-link" href="{% url 'admin:index' %}">Admin</a></li>
          <li><a class="nav-link" href="{% url 'basic_app:other'%}">Other</a></li>
        </ul>

      </div>
    </nav>

    <div class="container">

        {% block body_block %}
        <!-- anything outside of this will be inherited if you extend -->
        {% endblock %}
    </div>

  </body>
</html>

learning_templates/basic_app/templates/basic_app/index.html
<!DOCTYPE html>
{% extends "basic_app/base.html" %}
  {% block body_block %}
    <h1>Welcome to index!</h1>
    <h2>This is index.html page showing!</h2>
    <p>virtualenv: myDjangoEnv <br>
      開始專案: django-admin startproject projectname <br>
      進入 projectname資料夾中 <br>
      建立新的app: django-asmin startapp appname <br>
    </p>
  {% endblock %}

learning_templates/basic_app/templates/basic_app/other.html
<!DOCTYPE html>
{% extends "basic_app/base.html" %}
  {% block body_block %}
    <h1>Welcome to other!</h1>
    <h2>This is an example of template inheritance!</h2>
  {% endblock %}

learning_templates/basic_app/templates/basic_app/relative_url_templates.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title></title>
  </head>
  <body>
    <h1>WELCOME TO RELATIVE URL TEMPLATES</h1>
    <a href="{% url 'basic_app:other' %}">THE OTHER PAGE</a>
    <a href="{% url 'admin:index' %}">link to admin.index<a>
    <a href="{% url 'index' %}">Go back to index</a>
  </body>
</html>